# Generated by Django 4.1.5 on 2023-02-05 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, help_text='Product Colour', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product Name', max_length=100)),
                ('price', models.FloatField(help_text='Actual Price of Product')),
                ('discount_price', models.FloatField(blank=True, help_text='Discounted Price of Product', null=True)),
                ('fabric_type', models.CharField(blank=True, choices=[('chiffon', 'chiffon'), ('cotton', 'cotton'), ('silk', 'silk'), ('velvet', 'velvet'), ('synthetic', 'synthetic'), ('pending', 'pending'), ('denim', 'denim'), ('denim', 'denim'), ('linen', 'linen'), ('satin', 'satin')], help_text="Products' Fabric Type", max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Product Description', max_length=250, null=True)),
                ('size', models.CharField(blank=True, choices=[('extra_small', 'extra_small'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra large', 'extra large')], help_text="Products' size choice", max_length=100, null=True)),
                ('color_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profile.productcolor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
